<?php

/**
 * @file
 * Install, update and uninstall functions for the Media: Bynder module.
 */

/**
 * Implements hook_uninstall().
 */
function media_bynder_uninstall() {
  variable_del('media_bynder_url');
  variable_del('media_bynder_oauth_consumer');
  variable_del('media_bynder_oauth_consumer_secret');
  variable_del('media_bynder_oauth_token');
  variable_del('media_bynder_oauth_token_secret');
}
